---
- set_fact:
    overseer_normalized_name: "{{ overseer_name | regex_replace('[^-\\w]+', '-') | regex_replace('-{2,}', '-') | lower | trim }}"
    overseer_inventory: "{{ overseer_home }}/inventory"
    overseer_vars: "{{ overseer_home }}/vars"
    overseer_library: "{{ overseer_home }}/library"
    overseer_bin: "{{ overseer_home }}/bin"
    overseer_playbooks: "{{ overseer_home }}/playbooks"

- name: Ensure deb dependencies are installed.
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pip
    - python-dev
    - at
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure yum dependencies are installed.
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pip
    - python-devel
    - at
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon'

- name: Ensure python dependencies are installed.
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - boto
    - shyaml

- name: Ensure the overseer group exists.
  group:
    name: overseer
    state: present

- name: Ensure the overseer user exists.
  user:
    name: overseer
    group: overseer
    home: "{{ overseer_home }}"
    createhome: yes
    move_home: yes
    state: present

- name: Ensure necessary directories for overseer are created.
  file:
    path: "{{ item }}"
    owner: overseer
    group: overseer
    recurse: yes
    state: directory
  with_items:
    - "{{ overseer_inventory }}"
    - "{{ overseer_vars }}"
    - "{{ overseer_library }}"
    - "{{ overseer_playbooks }}"
    - "{{ overseer_bin }}"

- name: Ensure the EC2 dynamic inventory script is in place.
  get_url:
    url: https://raw.githubusercontent.com/ansible/ansible/devel/plugins/inventory/ec2.py
    dest: "{{ overseer_inventory }}/ec2.py"
    mode: ug+x
    force: yes

- name: Ensure the EC2 dynamic inventory module is correctly configured.
  copy:
    src: ec2.ini
    dest: "{{ overseer_inventory }}/ec2.ini"
    owner: overseer
    group: overseer

- name: Ensure there is a static inventory for local connections.
  copy:
    dest: "{{ overseer_inventory }}/local"
    content: |
      [localhost]
      127.0.0.1 ansible_connection=local

- name: Ensure the ec2 module will work with tags.
  get_url:
    url: https://raw.githubusercontent.com/wtcross/ansible-modules-core/ec2-start-stop-by-tag/cloud/amazon/ec2.py
    dest: "{{ overseer_library }}/ec2.py"
    owner: overseer
    group: overseer
    force: yes

- name: Ensure variables for this overseer are in place.
  template:
    src: overseer-vars.yml.j2
    dest: "{{ overseer_vars }}/{{ overseer_normalized_name }}.yml"

- name: Ensure overseer executables are in place.
  template:
    src: "bin/{{ item }}"
    dest: "{{ overseer_bin }}/{{ item }}"
    mode: "ug+rx,o-rwx"
  with_items:
    - enforce-check
    - enforce-stop
    - start-instances
    - stop-instances

- include: jobs/start-stop-schedule.yml
- include: jobs/enforcement.yml
